#+TITLE: 说中文的人容易犯的日文错误
#+DATE: [2019-08-25 Sun 16:45]


**** 错误1  喜欢在形容词后面加「の」
只有在 *名词修饰名词* 的时候才会加「の」，如果是 *形容词修饰名词* 或者 *动词修饰名词* 时都不需要加「の」，只要把名词放到形容词或动词之后就可以了。

例如：
+ 彼の携帯。（彼：名词・携帯：名词）（中译：他的手机）
+ *い* 形容詞修飾名詞的時候
  + 赤いりんご（い形容詞原形＋名詞）
  + 優しかった人（形容詞過去式＋名詞）

+ *な* 形容詞修飾名詞的時候
  + 綺麗な人（な形容詞原形＋名詞）
  + 綺麗だった人（な形容詞過去式＋名詞）

+ 形容詞否定句修飾名詞的時候
  + 優しくない人（い形容詞）
  + 綺麗ではない人（な形容詞）

+ 動詞修飾名詞的時候
  + 紅茶を飲んでいる人（動詞テイル形＋名詞）（正在喝紅茶的人）
  + 紅茶を飲んだ人（動詞た形＋名詞）（喝過紅茶的人）
  + 紅茶を飲む人（動詞原形＋名詞）（喝紅茶的人）

+ 動詞否定修飾名詞的時候
  + 動かない車（不動的車）
  + 魚を食べない人（不吃魚的人）

**** 错误2 「只要50元」的说法不是「50元だけです」
「だけ」確實是可以對應中文的「只（是）、只（要）」，但是在講述一個東西「很便宜」的時候，
用「だけ」反而是不自然的用法。

「だけ」表示限定的意思，所謂的限定就是「從一個群體裡面拿出一部份」的意思。
所以假如一個群體裡有男有女生的時候，在「女生」後面加上「だけ」，表示「只有女生可以參加，男生不行」。

#+BEGIN_QUOTE
「女性だけが参加できる」＝只有女生可以參加，男生不行
#+END_QUOTE

又如這句
#+BEGIN_QUOTE
「早餐只吃了麵包」=「朝ごはんはパンだけ食べた」。
#+END_QUOTE

假如我們設想「早餐」這個群體有包含「蛋、蘋果、麵包、牛奶⋯⋯」的時候，在「麵包」的後面加上「だけ」，表示一個群體裡只有「麵包」被限定，麵包以外的東西被排除在外。
但是像是以下句子「這本書只要50元」錯是因為「便宜或貴並不是一個群體」，所以用「だけ」會很不自然。

#+BEGIN_QUOTE
×「この本は50元だけです」
#+END_QUOTE

那這句怎麼改？
如果想要說「這東西很便宜」的時候只需要用「たった」就行了。
 
#+BEGIN_QUOTE
◯「この本はたったの50元です」（這本書只要50元）
#+END_QUOTE

**** 错误3 「た」跟「ている」的使用时机搞不清

狀況：進到房間裡看到有一隻蟑螂死在自己面前
 
想要描寫這句時，是不是很想寫「ゴキブリが死んだ」？
 
但是 錯！！
 
這個場景應該要說「ゴキブリが死んでいる」
為什麼呢？

「た形」表示過去式，所以蟑螂死「了」不是應該要用過去式嗎？
是這樣子沒錯，如果你確實看到蟑螂原本是活的但後來死掉的話，用「死んだ」是可以的。
但是，今天如果是，「你一進房間，就看到一個蟑螂屍體」的情況的話，你並沒有看到蟑螂死亡的瞬間，你只是看到「蟑螂死掉的狀態」的時候，就是要用「死んでいる」。

**** 错误4  尝尝漏掉格助词

我看過很多中文母語者寫的作文的時候，常常像下面句子一樣漏掉「が」、「に」、「で」之類的格助詞：

#+BEGIN_QUOTE
■大学生（が）よく行っている店
■彼はネットで収入（を）得る
#+END_QUOTE

由於中文都是用漢字表示句子的意思，沒有所謂的「格助詞」的概念，
所以我能理解大家常不小心用「中文思考」寫日文的時候會漏掉許多格助詞的心裡。
但是日文跟中文不同，在日文裡，若是要在句子裡添加意思的話，
必須用「が」、「に」、「で」、「を」這些格助詞來為句子添加意思。

而各個格助詞在文章裡所代表的作用整理如下：

+ 「が」：表示動作主。例：彼がよく運動をする。
+ 「に」：
  1. 表示動作向著的對象。例：父が母にプレセントをあげた。
  2. 表示場所。例：母が家にいる。
  3. 表示時間or空間的到達點。例：締め切りまでに提出してください。（在截止日前提交）
+ 「で」：
  1. 表示手段、方法。例：電車で行く。（搭電車去）
  2. 表示地點。例：公園でアイスを食べる。（在公園吃冰）
+ 「を」：
  1. 表示受動作影響的對象。例：母が妹を殴った。（媽媽打了妹妹)
  2. 表示人經過的路線。例：公園を通る。（穿過公園）

**** 错误5 「瓶子打不开」是「開けられない」还是「開かない」
日文中的自動詞跟他動詞也是學日文的一大障礙，這邊僅舉擁有自動詞他動詞對應的動詞來說。
比如說像是以下動詞:

表一 自他動詞對照表
| 自動詞     | 他動詞 |    
| 閉まる     | 閉める | 
| 開く       | 開ける |     
| 動く       | 動かす |     
| 割れる     | 割る   |     
| 建つ       | 建てる |     

他們各自發揮的機能如下：
 
+ ◯ 自動詞：表示物體或人產生的變化。前面沒有動作主，變化的物體後面接「が」。比如說：ドアが開いた。（門開了。ドア：變化物）


+ ◯ 他動詞：有一個動作主讓物體或人產生變化。一定有一個動作主存在，被變化的物體後面接「を」。比如說：彼がドアを開けた。（他把門打開了。彼：動作主，ドア：被產生變化的物體）


而在標題的「瓶子打不開」這句話裡面，在中文的視角會覺得「我是做動作的人，瓶子打不開是因為我打不開」，所以很容易用他動詞的能力形「開けられない」來描述這個狀況。


但是以日文的視角來說，重點放在「“瓶子”打不開」上，所以日文會用「瓶が開かない」來形容這個狀況。


Reference:
+ https://monstera.funique.info/doc/890db94c5dfa8d990e5ce967bc76fdb7
