#+TITLE: Java 环境变量设置
#+DATE: [2019-04-15 Mon 15:06]

*** 设置环境变量 

在home当前目录下用编辑器打开.zshrc文件并将下面内容添加到其内。
#+BEGIN_EXAMPLE
##JAVA ENVIROMENT                                                                                                     
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
#+END_EXAMPLE
添加完毕后记得执行source .zshrc使其生效。

*** 关于classpath中jar包的含义

dt.jar和tools.jar位于：{Java_Home}/lib/下，而rt.jar位于：{Java_Home}/jre/lib/下,其中：

rt.jar是JAVA基础类库，也就是你在java doc里面看到的所有的类的class文件
dt.jar是关于运行环境的类库

tools.jar是工具类库,编译和运行需要的都是toos.jar里面的类分别是sun.tools.java.*; sun.tols.javac.*;

 
在Classpath设置这几个变量，是为了方便在程序中 import；Web系统都用到tool.jar。
1. rt.jar
    rt.jar 默认就在Root Classloader的加载路径里面的，而在Claspath配置该变量是不需要的；同时jre/lib目录下的

    其他jar:jce.jar、jsse.jar、charsets.jar、resources.jar都在Root Classloader中

2. tools.jar

    tools.jar 是系统用来编译一个类的时候用到的，即执行javac的时候用到

    javac XXX.java

    实际上就是运行

    java -Calsspath=%JAVA_HOME%\lib\tools.jar xx.xxx.Main XXX.java

    javac就是对上面命令的封装 所以tools.jar 也不用加到classpath里面

3. dt.jar
    dt.jar是关于运行环境的类库,主要是swing的包   在用到swing时最好加上。

*** source link

- [[https://www.cnblogs.com/jtlgb/p/6039809.html][JDK中rt.jar、tools.jar和dt.jar作用]]
- [[https://www.cnblogs.com/havenshen/p/3490448.html][mac OS X 10.9.1 配置jdk环境变量]]
