#+TITLE: 工具清单
#+AUTHOR: Siqing Mu
#+DATE: 2019-01-26

** 我都在用哪些工具？

*** 首先是有关英语学习及阅读的软件
作为一名程序员，我一直觉得英语是每个人最应该掌握的基本语言，不管你是会写JAVA还是Python或者PHP，你都应该首先把英语这门语言学好。相信大多数人也都这么认为的。
但是话虽这样说，但实际上我们每天常常被困囿在繁重的工作当中，可利用的时间很少，这可能是个借口，但确是不可否认。

我觉得程序员群体大多视野狭隘，自负的人常常把技术当作自己唯一值得炫耀的资本，谦逊的人又会把提升个人能力和技术作为生活中的绝大部份甚至全部。当然这里面带有我绝对的主观偏见。
但生活不是这样子的，人生也不应该这样过。就像在你读书上学期间，你可能会有各个科目打分，以此来判断你是否偏科。但生活从来不会给你打分，如果你觉得有个东西在衡量那不过是你主观认为。
就像时间，时间存在吗，时间不存在吗，那不过是我们用树木的枯朽，人的轮回来作为表示，扯远了，哈哈。但我们需要平衡，需要去探索更多未知的发现。

好吧，我跑题跑太远了，让我们说说工具吧。

-【不背单词】一个背单词软件，我每天都会用

-【Eudic】 这个软件也不错，最开始我就是用它，之后转用「不背单词」，现在偶尔也用。桌面版也非常好。

- 当然还有很多比如「英语流利说」「扇贝单词」「百词斩」「多邻国」「极光单词」等等太多，我使用过后，觉得上面两个更适合我些。下面重点说说这个软件。

-【彩云小译】这个软件改变了我，最近一直在用，并且加入了会员计划，每个月仅需八元，也有朋友觉得贵，但我觉得如果一个软件工具能够帮助我更快地阅读和获取新知识，我会毫不犹豫的买下它。
这个软件它有个浏览器（chrome）扩展，非常好用，我每天阅读 「hacker news」时候都会用到它，之前是用google家的translate，现在有了它，我几乎不用再费劲查翻译了，但还是会用到它，比如有些
翻译不准确的，还是会去用google translate翻译下的。继续说彩云小译这个插件，它会以对照的形式翻译文章，遇到不通顺的你稍微瞅下上面的原文应该也能明白，实在不明白就拿去google translate一下。
不多说了，用就是了，相信会对你有帮助。

*** 关于API管理调试工具

-【postman】这个软件相信大家都知道的，也就不多说了，有免费版也好像有付费版，如果你觉得没必要花钱能凑活用就行，那就它了。

-【Paw】没啥好说的，如果你想要更好的体验和管理你的API，那就是它了。我好像是两年前买的，当时花了$49.99，当时软件也不太稳定有一些bug，现在好多了。这里要提醒你的是，如果你试用之后决定要买，不妨等到黑五再入手，那时会半价销售。





