#!/bin/bash
# publish org files.

# find emacs binary.
kernel=`uname -s`
emacs="emacs"
if [ $kernel"X" == "DarwinX" ]
then
    emacs="/usr/local/bin/emacs"
fi

git pull origin master

# generate html files.
$emacs --batch --script ./scripts/publish.el
if [ $? != 0 ]
then
    echo "publish failed!"
    exit 1
fi

# post processing html files.
./scripts/gen-404
git add .
git commit -a -m 'xy'
git push origin master
